### ISSUE TITLE
Task due dates missing in backlog

### ISSUE THREAD

**Issue by baba43** [mwakerman/kanbanist#48] opened 2019-09-06 06:41 UTC
Currently, the Board isn't listing untagged tasks anymore and also there isn't an option to enable it, is it?

**Comment by mwakerman** [comment] 2019-09-06 07:51
Are you referring to the Backlog?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwakerman** [comment] 2019-09-06 07:51
(Which is where tasks that do not have a label/list go)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by baba43** [comment] 2019-09-06 07:54
You're right, but my Backlog is empty. 

My previous workflow (that was working for a long time) is to just filter by _today_ so that I get an overview about my daily (and overdue) tasks, grouped by List. 

However, as soon as I select the date, my Backog is empty now.

**Comment by mwakerman** [comment] 2019-09-06 11:13
That sounds like a bug. I’ll take a look, Todoist end-of-lifed the API I was using and I updated it on Tuesday to use the new API but didn’t have time to test it thoroughly .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by msantoro14** [comment] 2019-09-30 13:30
Hi There @mwakerman , I noticed this change write away as well.  The workflow worked well from dragging items from back log to a filter every day.  It was a great work process.  However, when you filter by "today" all of the backlog disappears as noted above.  Would be great to have this bug fixed.  Thank you for creating such a useful tool and for all of your time and effort to support it. =)

**Comment by baba43** [comment] 2019-11-21 19:04
@mwakerman it would be awesome if you find time to fix this issue. If it's just a small change, it will make your app so much more powerful. If not, tell us if/what's the problem.

Thank you! 👍

**Comment by mwakerman** [comment] 2019-11-22 06:27
I've had a look and it's not clear to me that something has 'changed'.

- My backlog is working correctly and all tasks that do not have a "label" appear in the backlog.
-  Regarding @msantoro14's comment, selecting "Today" filters my board to all tasks due today (or overdue). This filtering includes the filtering the backlog (and always has). It actually doesn't make sense to not filter the backlog and then allow people to drag tasks from the backlog and have them instantly disappear.

Please let me know if I've missed something but I'm unable to see a bug/change in behavior. I believe the first comment on this issue may have been  @baba43 not realizing they had a filter currently applied.

**Comment by baba43** [comment] 2019-11-22 07:08
@mwakerman thank you very much. The issue still exists (at least for me) and can be easily reproduced:

Add a new task to Todoist with a due date of today. Then go it Kanban.ist and filter by that date. Now, the Backlog is empty and my task isn't shown anywhere. The only way to get it shown again is by specifing a label. In other words, it's impossible to have tasks without a label to show up when filtering by date.

Maybe you can't reproduce this for whatever reason (then we have to find out why) but I believe that @Nornwen and @msantoro14 are referring to the exact issue as well.

**Comment by msantoro14** [comment] 2019-11-22 13:32
@baba43 and @mwakerman , yes I agree with @baba43 , the previous version of the backlog workflow functionality was useful and necessary.  Add any task and assign it "Today" and it used to automatically appear in the backlog even without a label.  Then you could always filter what you viewed in the backlog by using the project filter or priority filter and "today." filter.  But now, as @baba43 mentioned and I will expand...you can indeed see all items in your backlog as long as you don't have the "Due Date" Filter activated.  So you can see a list of tasks without a label in your backlog for any and all dates, but once you select "Today," in order to organize your daily tasks and usefully transfer them from one list/label to another (which is really the point of using Kanbanist), every task without a label disappears from the backlog.  Somehow the "Backlog" feature in Kanbanist is not functioning properly with the "Due Date" filter.  As you can imagine, when it was working properly it was rather beautiful...you can see all of today's tasks in your backlog and determine which needed to be dragged to your "work to do" list/label for the day and then and then operate from the "Work to do" list and your off an running for the day.  Unfortunately, since the bug, it's too easy for tasks to fall through the cracks right now if you forget to add a label.  Hope this information is helpful to correct the backlog "due date" filter bug.  Thank you @mwakerman we really appreciate your work.

**Comment by baba43** [comment] 2020-01-25 11:03
@mwakerman may you have a look into this one more time please?

I would really love to use Kanbanist again.

**Comment by mwakerman** [comment] 2020-01-29 01:24
@baba43 - I had another look and your reproduction steps were correct. The underlying issue was that all tasks in the backlog were incorrectly being created with no due date (ignoring the due date from the task in Todoist). This was missed in the migration from Todoist API v7 → v8.

**Closed by mwakerman** 2020-01-29 01:24 UTC

**Comment by msantoro14** [comment] 2020-03-03 13:27
@mishawakerman and @baba43 I noticed the issue we have been discussing has been resolved with the most recent update.  It's working well again now!  Thank you!
