### ISSUE TITLE
Support for Mobile Web or Mobile app

### ISSUE THREAD

**Issue by jojipjohn** [mwakerman/kanbanist#36] opened 2019-02-16 18:27 UTC
Please add support for Mobile Web or Mobile app. This will be a help for users who are using Todist on Mobile.

Joji John

**Comment by dbarnett** [comment] 2019-12-05 15:25
There's #22 for an Android app. One of them should be closed as dupe.

**Comment by mwakerman** [comment] 2019-12-08 23:39
Thanks @dbarnett, closing as dupe of #22.

**Closed by mwakerman** 2019-12-08 23:39 UTC
Labels: enhancement
